# Generated by Django 4.2.6 on 2024-01-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='sentiment',
            field=models.CharField(max_length=50),
        ),
    ]
